<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\FlashSaleDB\FlashSaleDB\FlashSaleDB.csproj" />
    <ProjectReference Include="..\E-commerceFlashSale.Domain\UserManagement.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Common\" />
    <Folder Include="Exceptions\" />
    <Folder Include="Contracts\" />
    <Folder Include="Handlers\" />
    <Folder Include="Queries\" />
    <Folder Include="Validators\" />
    <Folder Include="Profiles\" />
  </ItemGroup>

</Project>
